package Group;


/**
* Group/CRUD_Falae.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Group_Module.idl
* Terça-feira, 3 de Maio de 2016 21h51min18s BRT
*/

public interface CRUD_Falae extends CRUD_FalaeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CRUD_Falae
