package Group;


/**
* Group/CRUD_FalaeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Group_Module.idl
* Terça-feira, 3 de Maio de 2016 21h51min18s BRT
*/

abstract public class CRUD_FalaeHelper
{
  private static String  _id = "IDL:Group/CRUD_Falae:1.0";

  public static void insert (org.omg.CORBA.Any a, Group.CRUD_Falae that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Group.CRUD_Falae extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Group.CRUD_FalaeHelper.id (), "CRUD_Falae");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Group.CRUD_Falae read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CRUD_FalaeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Group.CRUD_Falae value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Group.CRUD_Falae narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Group.CRUD_Falae)
      return (Group.CRUD_Falae)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Group._CRUD_FalaeStub stub = new Group._CRUD_FalaeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Group.CRUD_Falae unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Group.CRUD_Falae)
      return (Group.CRUD_Falae)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Group._CRUD_FalaeStub stub = new Group._CRUD_FalaeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
