package Group;

/**
* Group/CRUD_FalaeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Group_Module.idl
* Terça-feira, 3 de Maio de 2016 21h51min18s BRT
*/

public final class CRUD_FalaeHolder implements org.omg.CORBA.portable.Streamable
{
  public Group.CRUD_Falae value = null;

  public CRUD_FalaeHolder ()
  {
  }

  public CRUD_FalaeHolder (Group.CRUD_Falae initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Group.CRUD_FalaeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Group.CRUD_FalaeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Group.CRUD_FalaeHelper.type ();
  }

}
