package Corba;


/**
* Corba/CORBA_Falae.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/CORBA_Module.idl
* Sábado, 28 de Maio de 2016 13h14min26s BRT
*/

public interface CORBA_Falae extends CORBA_FalaeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBA_Falae
